0. Libraries 

```{r}
library(tidyverse)
library(cowplot)
library(RColorBrewer)
library(gapminder)
library(plotly)
```

1. Enviromental conditions mean

```{r}
plot_data_mean <- function (column, col_name){
 ggplot(train, aes(Occupancy, column, fill=Occupancy))+
   geom_bar(stat = "summary", 
             fun.y = "mean",
             width= 0.3,
             position = position_dodge(width = 0)) + 
   scale_fill_brewer(palette="Pastel2") +
    labs(x="",
         y=col_name)+
   theme_minimal() +
   theme(legend.position = "bottom",
         text = element_text(family="Raleway"))
    
}

conditions_mean <- ggarrange(plot_data_mean(train$Temperature, "Temperature (°C)"), plot_data_mean(train$Humidity, "Humidity (%)"), plot_data_mean(train$Light, "Light (Lux)"), plot_data_mean(train$CO2, "CO2 (ppm)"), nrow = 2, ncol=2,common.legend = TRUE, legend="bottom")

annotate_figure(conditions_mean, top =  text_grob("Enviromental conditions mean", size = 16, family="Raleway"))
```

2. Enviromental conditions over time

```{r}
plot_time_series <- function (column, col_name){
 ggplot(train, aes(date, column, color=Occupancy))+
   geom_line() +
   scale_fill_brewer(palette="Pastel2") +
    labs(x="",
         y=col_name)+
   scale_x_datetime(date_labels = "%a \n %d-%m \n", breaks = "24 hours" ) +
   theme_minimal() +
   theme(legend.position = "bottom",
         text = element_text(family="Raleway"))
}

series_plot <- ggarrange(plot_time_series(train$Temperature, "Temperature (°C)"), plot_time_series(train$Humidity, "Humidity (%)"), plot_time_series(train$Light, "Light (Lux)"), plot_time_series(train$CO2, "CO2 (ppm)"), nrow = 4,common.legend = TRUE, legend="bottom", heights = c(3, 3,3,3))

annotate_figure(series_plot, top =  text_grob("Enviromental conditions over time", size = 16, family="Raleway"))
```

3. Light over time

```{r}
light_plot <- ggplot(data = train, aes(date, Light, color = Occupancy)) + 
  geom_point(size=0.8) +
  scale_x_datetime(date_labels = "%a \n %d-%m \n", breaks = "24 hours" ) +
  scale_color_manual(values=brewer.pal(name ="Pastel2", n = 2)) + 
  labs(x = "Date", 
       y = "Light (Lux)",
       title = "Illuminance level over time") +
  theme_minimal() + 
  theme(plot.title = element_text(hjust = 0.5, vjust = 2, size = 16, face = "italic"),
        legend.title = element_text(size = 10),
        legend.text = element_text(face = "bold"),
        legend.position = "bottom",
        legend.box = "vertical",
        legend.key = element_rect(fill = "#f0f0f0", color = NA))+
  guides(color = guide_legend(override.aes = list(size=4)))

  
light_plot_ly <- ggplotly(light_plot)
htmltools::save_html(light_plot_ly, "light_graph.html")
```
[Click here to view the interactive plot](light_graph.html)

4. CO2 over time

```{r}
CO2_plot <- ggplot(data = train, aes(date, CO2, color = Occupancy)) + 
  geom_point(size=0.8) +
  scale_x_datetime(date_labels = "%a \n %d-%m \n", breaks = "24 hours" ) +
  scale_color_manual(values=brewer.pal(name ="Pastel2", n = 2)) + 
  labs(x = "Date", 
       y = "CO2 (ppm)",
       title = "CO2 over time") +
  theme_minimal() + 
  theme(plot.title = element_text(hjust = 0.5, vjust = 2, size = 16, face = "italic"),
        legend.title = element_text(size = 10),
        legend.text = element_text(face = "bold"),
        legend.position = "bottom",
        legend.box = "vertical",
        legend.key = element_rect(fill = "#f0f0f0", color = NA))+
  guides(color = guide_legend(override.aes = list(size=4)))

ggplotly(CO2_plot)
```
-----------------NEW FEATURES-----------------

5. Humidity change over time

```{r}
humchange_plot <- ggplot(data = train, aes(date, hum_change, color = Occupancy)) + 
  geom_point(size=0.8) +
  geom_line(width=0.1) +
  scale_x_datetime(date_labels = "%a \n %d-%m \n", breaks = "24 hours" ) +
  scale_color_manual(values=brewer.pal(name ="Pastel2", n = 2)) + 
  labs(x = "Date", 
       y = "Humidity change",
       title = "Humidity change over time") +
  theme_minimal() + 
  theme(plot.title = element_text(hjust = 0.5, vjust = 2, size = 16, face = "italic"),
        legend.title = element_text(size = 10),
        legend.text = element_text(face = "bold"),
        legend.position = "bottom",
        legend.box = "vertical",
        legend.key = element_rect(fill = "#f0f0f0", color = NA))
 ```{r}
